
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: safestore
      POSTGRES_USER: safeuser
      POSTGRES_PASSWORD: safepassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
